# Some other Java library that the GWT application depends on. This library might
# or might not have been created with GWT in mind, but if you want to use GWT
# classes you should probably depend on "//external:gwt-user".
java_library(
    name = "lib",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//external:gwt-user",
    ],
)
